name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run Maven Tests
        run: mvn -B test
  
  build:
    needs: test #นผ.เพิ่ม
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pattaratos/arainea-backend:latest
    - name: Build Database image
      run: docker build . --file src/main/resources/persistence/Dockerfile --tag pattaratos/arainea-database:latest
    - name: login
      run: docker login -u pattaratos -p dckr_pat_sJjyI445b42CCn2vjtYA9dMs5Po
    - name: push docker backend
      run: docker push pattaratos/arainea-backend:latest
    - name: push docker database
      run: docker push pattaratos/arainea-database:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout Backend repo
        uses: actions/checkout@v4
  
      - name: Checkout Deployment repo
        uses: actions/checkout@v4
        with:
          repository: AraiNea/Deployment
          path: deployment

          
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
  
      - name: Apply manifests
        run: |
          kubectl apply -f deployment/k8s/namespace.yaml || true
          sleep 5
          kubectl apply -f deployment/k8s/
